Fix getReflectionsFromSymbolId to filter undefined reflections.
getReflectionsFromSymbolId can return [undefined] in certain situations, causing downstream null pointer exceptions.

```
TypeError: Cannot read properties of undefined (reading 'kindOf')
    at ./node_modules/typedoc/dist/lib/models/types.js:688:25
    at Array.find (<anonymous>)
    at get reflection [as reflection] 
```