Fix getReflectionsFromSymbolId from returning undefined elements
Returning [undefined] causes downstream TypeErrors.

Example:
```
TypeError: Cannot read properties of undefined (reading 'kindOf')
    at ./node_modules/typedoc/dist/lib/models/types.js:688:25
    at Array.find (<anonymous>)
    at get reflection [as reflection]
```